---
title: "ANA 515 Assignment 1"
author: "Emmanuel Assenso Antwi"
date: "2022"
output: 
   html_document:
          theme:
              bootswatch: minty

  
---
  
```{r setup, include = FALSE}
#install.packages("tidyverse")
#install.packages("knitr")
#install.packages("dplyr") from tools
#loading the installed packages
library(tidyverse)
library(knitr)
library(dplyr)
```

```{r get data, include = FALSE}
url <- 'https://raw.githubusercontent.com/fivethirtyeight/guns-data/master/full_data.csv'
gun_deaths <- read_csv(url)
glimpse(gun_deaths)
```

```{r data-manipulation, include = FALSE}
youth <- gun_deaths %>%
  filter(age <= 65)
summary(youth)
```

```{r, echo = FALSE}
#This next chunk is inline code. Inline code puts the text with the output of the function in my document.
```

We have data about `r nrow(gun_deaths)` individuals killed by guns. Only `r nrow(gun_deaths) - nrow(youth)` are older than 65. The distribution of the remainder is shown below:
  
#Gun deaths by age
  
```{r youth-dist, echo = FALSE}
library(ggplot2)
youth %>%
  ggplot(aes(age))+geom_freqpoly(binwidth = 1)
```

#Gun deaths by race

```{r race-dist, echo = FALSE}
youth %>%
  ggplot(aes(fct_infreq(race) %>% fct_rev())) +
  geom_bar() + coord_flip() + labs(x = "Victim race")
```

```{r, echo = FALSE}
#Once all of my code has been written, I click on the Knit button in the tool bar above to produce my document.
```


